name: JOSS figure generation
on:
  push:
    paths:
      - joss_paper/create_paper_plots.jl
      - .github/workflows/joss_figures.yml

jobs:
  figures:
    name: joss-figures
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --project=joss_paper -e '
            save_plots=true
            include("joss_paper/create_paper_plots.jl")'

      - name: Commit plots to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "(auto) Paper plot adding"
          # This should be the path to the paper within your repo.
          add: "joss_paper/plots" # 'paper/*.pdf' to commit all PDFs in the paper directory
