name: JOSS figure generation
on:
  push:
    paths:
      - joss_paper/create_paper_plots.jl
      - .github/workflows/joss_figures.yml

jobs:
  figures:
    name: joss-figures
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: julia-actions/cache@v1
      - run: |
          julia --project=joss_paper -e '
            using Pkg
            Pkg.instantiate()
            save_plots=true
            include("joss_paper/create_paper_plots.jl")'

      - name: Commit plots to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "(auto) add joss paper plots"
          # This should be the path to the plots within your repo.
          add: "joss_paper/plots"
  paper: # trigger paper workflow
    needs: figures
    uses:
      ./.github/workflows/joss.yml
